config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  get 'cards/new'
  get 'comments/new'
  get 'items/search'
  
  root to: 'items#index'
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end
   resources :users, only: [:new, :show]
   resources :cards, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials
  has_many :items
  has_many :orders
  has_many :comments
  has_one :card, dependent: :destroy

  with_options presence: true do
    validates :nickname
    validates :birth_date

    with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: '全角文字を使用してください' } do
      validates :first_name
      validates :last_name
    end

    with_options format: { with: /\A[ァ-ン]+\z/, message: '全角文字(カタカナ)を使用してください' } do
      validates :last_name_kana
      validates :first_name_kana
    end
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create

    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )

    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]

    if @user.persisted? # ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else # ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @nickname = current_user.nickname
    @items = current_user.items

    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    card = Card.find_by(user_id: current_user.id)

    # redirect_to new_card_path and return unless card.present?
    if card.present?
      customer = Payjp::Customer.retrieve(card.customer_token)
      @card = customer.cards.first
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/second-header"%>
<%# if user_signed_in? && current_user.nickname == @nickname %>
<%#= link_to "マイページ設定", new_card_path(current_user), id: "setting" %>
<%# end %>

<%= form_for(current_user) do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <% if @card.present? %>
    <div class='credit-card-form'>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">カード情報</label>
            <span class="indispensable">必須</span>
          </div>
          <%= "**** **** **** " + @card[:last4] %>
          <div class='available-card'>
            <%= image_tag 'card-visa.gif', class: 'card-logo'%>
            <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
            <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
            <%= image_tag 'card-amex.gif', class: 'card-logo'%>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">有効期限</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='input-expiration-date-wrap'>
            <%= @card[:exp_month] %>
            <p>月</p>
            <%= @card[:exp_year] %>
            <p>年</p>
          </div>
        </div> 
    </div>
  <% end %>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      
    </div>
    <%= current_user.nickname %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      
    </div>
    <%= current_user.email %>
  </div>
  
  
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      
    </div>
  
      <%= current_user.last_name %>
      <%= current_user.first_name %>
   
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      
    </div>
    
      <%= current_user.last_name_kana %>
      <%= current_user.first_name_kana %>
   
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      
    </div>
    <div class='input-birth-wrap'>
      <%= current_user.birth_date %>
    </div>
     <br>
  </div>
  
<% end %>
<div class="item-show">
  <h1 class="search-result">
    出品している商品一覧
  </h1>
<% if @items.length !=0 %>
    <% @items.each do |item| %>
      <br>
      <div class="item-box">
          <div class="item-explain-box">
            <h2 class="name">
              <%= item.name %>
            </h2>
          </div>
          <div class="item-img-content-show">
            <% item.images.each do |image| %>
              <%= image_tag image, class:'item-box-img' %>
            <% end %>
          </div>
          <div class="item-price-box">
            <span class="item-price">
              <%= item.price %>
            </span>
            <span class="item-postage">
              <%= item.shipping_fee_status.name %>
            </span>
          </div>
          <% if user_signed_in? && item.order.nil? %>
            <% if current_user.id == item.user_id %>
            <%= link_to "商品の編集", edit_item_path(item.id), method: :get, class: "item-red-btn" %>
            <p class="or-text">or</p>
            <%= link_to "削除", item_path(item.id), method: :delete, class:"item-destroy" %>

            
            <% else %>
            <%= link_to "購入画面に進む", item_orders_path(item.id),class:"item-red-btn"%>
            <% end %>
         <% end %>
        </div>
        <div class="item-explain-box">
          <span><%= item.info %></span>
        </div>
        <table class="detail-table">
          <tbody>
            <tr>
              <th class="detail-item">出品者</th>
              <td class="detail-value"><%= item.user.nickname %></td>
            </tr>
            <tr>
              <th class="detail-item">カテゴリー</th>
              <td class="detail-value"><%= item.category.name %></td>
            </tr>
            <tr>
              <th class="detail-item">商品の状態</th>
              <td class="detail-value"><%= item.sales_status.name %></td>
            </tr>
            <tr>
              <th class="detail-item">配送料の負担</th>
              <td class="detail-value"><%= item.shipping_fee_status.name %></td>
            </tr>
            <tr>
              <th class="detail-item">発送元の地域</th>
              <td class="detail-value"><%= item.prefecture.name %></td>
            </tr>
            <tr>
              <th class="detail-item">発送日の目安</th>
              <td class="detail-value"><%= item.scheduled_delivery.name %></td>
            </tr>
          </tbody>
        </table>
    <% end %>
  <% else %>
  <div class="no-result">
    出品している商品はありません
  </div>
  <% end %>
  <br>
</div>
<%= render "shared/second-footer"%>
<% breadcrumb :user_show %>